# Generated by Django 2.0.7 on 2023-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('target_language', models.CharField(max_length=100)),
                ('project_ID', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
