# Generated by Django 2.0.7 on 2023-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_ID',
            field=models.CharField(default='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>', max_length=255, unique=True),
        ),
    ]
