# Generated by Django 2.0.7 on 2023-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20230316_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_ID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
