# Generated by Django 2.0.7 on 2023-03-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0003_auto_20230316_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_ID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('original_string', models.CharField(max_length=10000)),
                ('translated_string', models.CharField(max_length=10000)),
                ('project_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Projects.Project')),
            ],
        ),
    ]
