# Generated by Django 2.0.7 on 2023-03-17 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceId', models.IntegerField()),
                ('originalSentence', models.CharField(max_length=500)),
                ('translatedSentence', models.CharField(max_length=500, null=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
