# Generated by Django 2.0.7 on 2023-03-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_auto_20230318_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
