# Generated by Django 2.0.7 on 2023-03-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotator',
            field=models.CharField(default='kunal', max_length=100),
        ),
    ]
